export const APP_THEMES = [
  'theme-light',
  'theme-dark',
  'theme-jarvis',
  'theme-neon-pink',
  'theme-solar-flare',
  'ocean',
  'forest',
  'sunset',
  'midnight',
  'lavender',
  'mint',
  'rose',
  'amber',
  'teal',
  'indigo',
  'coral',
  'sage',
  'crimson',
] as const;

export const THEME_OPTIONS: Array<{ name: string; value: (typeof APP_THEMES)[number] }> = [
  { name: 'Light', value: 'theme-light' },
  { name: 'Dark', value: 'theme-dark' },
  { name: 'Jarvis', value: 'theme-jarvis' },
  { name: 'Neon Pink', value: 'theme-neon-pink' },
  { name: 'Solar Flare', value: 'theme-solar-flare' },
  { name: 'Ocean', value: 'ocean' },
  { name: 'Forest', value: 'forest' },
  { name: 'Sunset', value: 'sunset' },
  { name: 'Midnight', value: 'midnight' },
  { name: 'Lavender', value: 'lavender' },
  { name: 'Mint', value: 'mint' },
  { name: 'Rose', value: 'rose' },
  { name: 'Amber', value: 'amber' },
  { name: 'Teal', value: 'teal' },
  { name: 'Indigo', value: 'indigo' },
  { name: 'Coral', value: 'coral' },
  { name: 'Sage', value: 'sage' },
  { name: 'Crimson', value: 'crimson' },
];
