import type { Metadata } from 'next';
import ViralTrendsClient from './viral-trends-client';

export const metadata: Metadata = {
  title: 'Viral Social Media Titles & Hook Templates | Rachna Rivo',
  description: 'Analyze viral title formats, hook designs, description templates, and actionable content suggestions to boost your performance on YouTube, Instagram, and TikTok.',
  keywords: [
    'viral titles',
    'hook templates',
    'video titles',
    'social media descriptions',
    'video click-through rate',
    'rachna rivo'
  ],
  alternates: {
    canonical: 'http://localhost:3000/viral-trends',
  },
};

const viralFaqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "How does Rachna Rivo help write viral titles?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Rachna Rivo uses AI models to analyze past viral headline formulas and suggests structured title formats (e.g. comparison hooks, curiosity hooks) you can instantly adapt."
      }
    },
    {
      "@type": "Question",
      "name": "What strategies are recommended for high description engagement?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We recommend placing a strong primary hook in the first 2 lines, followed by structured timeline links, helpful resource resources, and relevant keywords to rank on search indexes."
      }
    }
  ]
};

export default function ViralTrendsPage() {
  return (
    <div className="container mx-auto max-w-4xl p-4 md:p-8">
      <div className="text-center mb-8">
        <h1 className="mb-4 font-headline text-4xl font-bold">Viral Content Trends</h1>
        <p className="text-muted-foreground">
          Analyze viral formats, structures, and ideas generated by AI based on high-performing content.
        </p>
      </div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(viralFaqSchema) }}
      />
      <ViralTrendsClient />
    </div>
  );
}